#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define TRANSITION_TIME 0.5
#define CHARACTER_COLLISION_BITMASK 0x000001
#define FALLING_SPEED 0.0025
#define FLYING_SPEED 0.00375
#define FLY_DURATION 0.25

#endif // __DEFINITIONS_H__
